Write a sample that test whether a function is a recursion.
Coursemology/evaluator-samples pull request #11
Opened 2016-10-30 10:05 UTC by Teo-ShaoWei

This PR addresses issue #2.

@naomilwx is this the right way place to include the function?

2016-10-30 12:23 UTC, naomilwx commented on prog_question_test/tests/autograde.py
> +        self.meta['output'] = is_recursion(user_function)
should be `str(is_recursion(user_function))` because this is the printout of the result. Not sure if there will be implicit conversions though...

2016-10-30 12:27 UTC, naomilwx commented
Hmm do you intend for the test to be public or private

2016-10-30 12:31 UTC, Teo-ShaoWei commented
I think it make sense to be private. Public test is usually of the form `expr == value` where the student can copy as their own test case. Testing for recursion would be awkward in that form... It does however throw a helpful hint when violated. So it seems more like a private test to me.

2016-10-30 12:33 UTC, Teo-ShaoWei commented on prog_question_test/tests/autograde.py
> +        self.meta['output'] = is_recursion(user_function)
ok cool, done =)

2016-10-30 12:34 UTC, naomilwx commented on prog_question_test/tests/autograde.py
> +    def test_recursion(self):
should be `def test_private_recursion(self)`:

2016-10-30 12:40 UTC, Teo-ShaoWei commented on prog_question_test/tests/autograde.py
> +    def test_recursion(self):
Ok done! =)

2016-10-30 12:43 UTC, naomilwx commented on prog_question_test/tests/autograde.py
> +    def test_recursion(self):
weird, I'm not seeing the changes. You forgot to push?

2016-10-30 12:48 UTC, Teo-ShaoWei commented on prog_question_test/tests/autograde.py
> +    def test_recursion(self):
woot sorry, should be up le yupz

2016-11-24 16:13 UTC, fonglh requested changes
Just some minor comments

2016-11-24 16:13 UTC, fonglh commented on prog_question_test/tests/autograde.py
> +        self.meta['hint'] = 'Your function is not a recursion'
"Your function is not recursive."

2016-11-24 16:13 UTC, fonglh commented on prog_question_test/tests/autograde.py
> +                print(func_def_node)
Was this a debugging statement?

2016-12-05 09:37 UTC, Teo-ShaoWei commented on prog_question_test/tests/autograde.py
> +                print(func_def_node)
Yupz, sorry I should remove it >_<

2016-12-05 09:38 UTC, Teo-ShaoWei commented on prog_question_test/tests/autograde.py
> +        self.meta['hint'] = 'Your function is not a recursion'
Ok cool, changed.

2016-12-06 00:10 UTC, merged